version: "3.9"
services:
  back-end:
    build: ./server/
    restart: always
    env_file: .env
    environment:
      - DATABASE_URL="mysql://javauser:javapass@mariadb:3306/oncall"
      - PORT=5000
    ports:
      - 5001:5000
    networks:
      - db-network
      - app-network
  front-end:
    build: ./client/
    restart: always
    ports:
      - 3001:3000
    networks:
      - app-network
  db:
    image: mariadb:latest
    restart: always
    env_file: .env
    healthcheck:
      test: mariadb ${MARIADB_DATABASE} --user=${MARIADB_USER} --password='${MARIADB_PASSWORD}' --silent --execute "SELECT 1;"
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      db-network:
        aliases:
          - mariadb
    ports:
      - 42333:3306
    volumes:
      - mariadb-data:/var/lib/mysql
    

networks:
  app-network:
  db-network:

volumes:
  mariadb-data:

